### ISSUE TITLE
Feature request: Allow sharing of current coordinates

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#100]
From Sathya - Allow sharing of current coordinates:

I was recently asked if AppStudio could be used to build such an app: https://itunes.apple.com/us/app/my-gps-coordinates/id945482414?mt=8
 
My immediate reaction was this one screen app fits nicely in Trek2Threre and does not warrant a new app. The more I think the more I feel that adding this view of current coordinates with other useful info which can be copied and shared would be very useful.
 
-Sathya
 
Sathya Prasad
Group Engineering Manager & Software Development Lead
AppStudio + Esri Labs + Mercator + Survey123 + Story Maps
Esri, Redlands, California
909-793-2853 | @sathyaprasad

**Comment by dominikargast** [comment]
@marikavertzonis the coordinates can be copied to the clipboard by opening the location status pages (press on the satellite icon) and clicking on the values listed next to `Latitude`, `Longitude`, or `USNG`. Please test using 3.1.14

**Comment by marikavertzonis** [comment]
tested with 3.1.19 only on android 10 (don't have other devices with me at moment) and I see copy paste action works as expected.
