### ISSUE TITLE
Unable to connect to Bluetooth GPS devices on UWP

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#101]
Split off from #88 - this issue only refers to the UWP connection issue:

**anshuman-mathur commented on 20 Jun**

Tested Trek2There 3.0.36 Beta from HockeyApp which is built on AppFramework 3.1.58.

- ~~**Windows classic app:** Trek2There connects to a bluetooth GPS device successfully. However, when we try to change the device and connect to a different bluetooth GPS device, the app becomes non responsive and the title shows 'Not Responding'.~~

- **Windows UWP app:** The app does not finish connecting to the bluetooth GPS devices. The spinning image keeps on spinning indefinitely, indicating that the app is trying to connect to the GPS device.

**JohnHasthorpe commented on 25 Jun**

I could replicate the Windows issue, but not UWP. I was able to connect to a Bluetooth device without issues.

**Comment by dominikargast** [comment]
Related AppFramework issue: https://devtopia.esri.com/Melbourne/appstudio-framework/issues/692

**Comment by marikavertzonis** [comment]
Background work for this was completed, but with new Microsoft store capabilities and creation of MSIX files, work into supporting windows universal in AppStudio apps has been shelved, so closing this issue without a release version.
