### ISSUE TITLE
Fix anchors/layout mismatch errors

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#102]
After upgrading to Qt 5.11 a multitude of layout errors similar to the one below are reported in the console:

`file:///Users/dominik/Applications/Melbourne/Trek2There/controls/CustomizedDelegate.qml:12:9: QML Rectangle: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.`

`file:///Users/dominik/Applications/Melbourne/Trek2There/controls/CustomizedDelegate.qml:19:9: QML Row: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.`

This needs to be fixed.

**Comment by dominikargast** [comment]
@marikavertzonis please test with Trek2There 3.1.3 and check that no layout errors are reported in the console (may have to run from inside player)

**Comment by marikavertzonis** [comment]
* running trek2there 3.1.4 in appstudio 3.3.55 and in both Qt Creator and Visual Studio Codes console, i search for 'layout' and get nothing (no layout errors). the app runs as expected.
* installed trek2there 3.1.4 on iphone 6, pixel 2 and windows 10 also - and it works as expected
