### ISSUE TITLE
Update GNSSInfo plugin

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#103]
Update the GNSS handling to reflect the work done while introducing GNSS support in Survey123.

**Comment by dominikargast** [comment]
@marikavertzonis please test with Trek2There 3.1.3 and check that no connectivity issues have been introduced with updating the GNSS plugin.

**Comment by marikavertzonis** [comment]
tested build 3.1.4 on windows 10, iphone 6 and pixel 2 and successfully switch between external receivers and see expected distance and accuracy on main screen after switching
