### ISSUE TITLE
Update the location settings UI

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#104]
The location settings UI should be improved. Conform to the Survey123 layout.

**Comment by dominikargast** [comment]
Commit https://github.com/Esri/Trek2There/commit/1008db35f3370df367903871d1c7316fafc49301 was assigned an incorrect issue number (#40). It belongs to this issue.

**Comment by dominikargast** [comment]
@marikavertzonis please test the initial implementation with T2T 3.1.6.

At present, the detailed provider settings pages are accessible from the location provider page for testing purposes. These will likely be hidden in the future since they are not really relevant for T2T.

**Comment by marikavertzonis** [comment]
attempted to test with 3.1.6 (ios) and 3.1.7 (android) - white screen only on both

**Comment by shobanasuresh** [comment]
Console log for white screen

```
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/Trek2There.qml:113:5: Type MainView unavailable
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/views/MainView.qml:63:9: Type NavigationView unavailable
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/views/NavigationView.qml:54:5: Type PositionSourceManager unavailable
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/GNSSPlugin/PositionSourceManager.qml:162:5: Type ConfirmPanel unavailable
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/GNSSPlugin/controls/ConfirmPanel.qml:268:17: Type ConfirmButton unavailable
02-27 17:08:23.404 26420 26436 W Trek2There: qrc:/qml/GNSSPlugin/controls/ConfirmButton.qml:21:1: "../Controls": no such directory
```

@dominikargast @marikavertzonis

**Comment by dominikargast** [comment]
@marikavertzonis fixed in 3.1.8

**Comment by marikavertzonis** [comment]
- testing with 3.1.8 on samsung s9  and iphone 8 with bluetooth gps and network gps (trimble geoexplorer with gps gate)
- in general i can add a provider, see and amend the settings of the providers, and switch between providers
- problem with alerts
    - visual - what changes with this switch? currently you see the gps icon on the main page all the time. should this only be visible now when this option is on?
    - vibrate - on the samsung s9 (didn't see this on the iphone) the vibrate option is 'greyed out' even though on the same device the survey123 equivalent of this page DOES show the vibrate option (not greyed out)

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.1.9. The greyed-out vibration switch shout now work. The satellite icon has been replaced with a new one, indicating connection state as in Survey123. Pressing the icon will open up the satellite info pages.

**Comment by marikavertzonis** [comment]
- testing with 3.1.10 on pixel 2 and iphone 6 with 2 bluetooth gps 
- i now see the vibrate switch enabled on both
- the visual alert swtich disables/enables the alert messages on screen
- i see the same searching and blinking gps as in survey123

but
- have two bluetooth gps configured, and one connected. change the name of the not-connected one. see that the name of the connected one changes to the new name

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.1.11

**Comment by marikavertzonis** [comment]
- testing with 3.1.12 on samsung s9 and iphone 8 with 2 bluetooth gps 
- i see the vibrate switch enabled on both
- the visual alert switch disables/enables the alert messages on screen
- i see the same searching and blinking gps as in survey123
- i can switch between 2 connected devices and change their names as expected. new names are remembered when i close and restart the app.

@dominikargast - the UI is behaving as expected at the moment. when you finish moving code around, reassign it to me and i'll verify and close.

**Comment by dominikargast** [comment]
@marikavertzonis code has been updated, test with 3.1.14

**Comment by marikavertzonis** [comment]
- testing with 3.1.15 on nokia 8 (android 10) and iphone 8 (ios 13.3.1) and windows surface pro 3 (windows 10) with the bad elf pro+ and juniper geode
- all alerts work as expected
- i can switch between 2 connected devices and change their names as expected. new names are remembered when i close and restart the app.
