### ISSUE TITLE
Update source code to run on Qt 5.15.2

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#105]
The code needs to be updated to reflect the API changes introduced in Qt 5.15.2.

**Comment by dominikargast** [comment]
@marikavertzonis code has been updated, test with 3.1.14

**Comment by marikavertzonis** [comment]
testing with 3.1.18 on nokia 8 (android 10) and iphone 8 (ios 13.3.1) and windows surface pro 3 (windows 10) with the bad elf pro+ and juniper geode
- switched between location providers, units, destination format, in the settings
- enabled / disabled aug reality
- launch from survey123 successfully and return to survey123 when tap 'end'
