### ISSUE TITLE
White screen on start up on Windows

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#107]
tested with 3.1.15 on Windows 10 - white screen only and app doesn't start.
Running the DebugView tool before launching T2T i see these debug msgs:
![image](https://user-images.githubusercontent.com/5713624/106806980-b4e93800-66bc-11eb-8353-209f8df58ef4.png)

**Comment by marikavertzonis** [comment]
we've now installed builds 3.1.16, 3.1.17 and 3.1.18 on other windows machines and they work fine. still get white screen on my surface pro 3. have deleted setting files and data files, uninstalled / reinstalled, to no avail. but cant reproduce. Leaving the issue open for me to continue troubleshooting, but removing from milestone.

**Comment by shobanasuresh** [comment]
@marikavertzonis Can you test if launching Trek2There.exe with `--renderingEngine angle` command line parameters resolves the white screen issue?

**Comment by marikavertzonis** [comment]
@shobanasuresh - tested with the command line parameters - no change (white screen only)

**Comment by marikavertzonis** [comment]
just as a matter of test progress, have now updated windows (and lots of drivers) to 20H2 - app still white screen on start up. also have used today build 3.1.19 (later build than previous, will have appstudio updates only, no app updates)

**Comment by marikavertzonis** [comment]
tested again - still white screen - t2t version 3.1.22 on same computer. current versions:

Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎17/‎02/‎2021
OS build	19042.1052

**Comment by marikavertzonis** [comment]
tested again - no white screen now! t2t2 version 3.1.24 (appframework version 5.3.99) on same computer. current versions: 

Edition Windows 11 Enterprise
Version 21H2
Installed on 8/‎11/‎2021
OS build 22000.493
