### ISSUE TITLE
Location accuracy indicator

### ISSUE THREAD

**Issue by spatialdude** [Esri/Trek2There#16]
A critical contributing factor to arrival detection and some of the observations in #13 is the **horizontalAccuracy** being reported by the location sensor.

The horizontal accuracy should somehow be displayed to the user. 

This could either as an absolute value as reported by the sensor -

e.g. For the distance to destination **123 m ± 10 m**

or a graphical representation such as signal strength

e.g. 

![image](https://cloud.githubusercontent.com/assets/7235583/18892351/8f647352-854c-11e6-9136-b95dc5672552.png)

The highest bar would be a location <= 10 m
The lowest bar would be > 100m

**Comment by marikavertzonis** [comment]
tested 1.0.27 on android 4.2 (CT4) and iOS 8.4 (iphone 5). The accuracy symbol does correspond to the text as expected. 

@defiantgoat - The bars do look a lot like network strength... could we experiment with concentric circles? Circles are used on maps to indicate accuracy... a bullseye may resemble those circles. Below is a crude example
![accuracy](https://cloud.githubusercontent.com/assets/5713624/22226824/2f1a2636-e21c-11e6-9f72-0409ff4c193c.PNG)

**Comment by defiantgoat** [comment]
I will test out a concentric circle version.

**Comment by defiantgoat** [comment]
Added as of v 1.1.9

![screen shot 2017-01-24 at 3 02 14 pm](https://cloud.githubusercontent.com/assets/3229911/22233698/20f08206-e246-11e6-891d-fc40f04acdf1.png)

May refine to 3 or 4 levels with color coordination
1: Red
2: Orange
3: Green

**Comment by marikavertzonis** [comment]
tested on tested on windows 10, ios 8.4 (iphone 6) and android 6.0.1 (samsung s6)
i can see the horizontal accuracy symbol on each device, and see it change. the symbol is quite small - but i think it standards out enough in the two blue color scheme. i could see it in bright sunlight and in shade. consider color change upon user feedback.
