### ISSUE TITLE
Update disabled arrow graphic in NavigationView

### ISSUE THREAD

**Issue by defiantgoat** [Esri/Trek2There#25]
When arrow is grayed out, it should be replaced with another graphic so user doesn't follow it.

**Comment by qhui-red** [comment]
No signal icon
[nosignal.svg.zip](https://github.com/Esri/Trek2There/files/739971/nosignal.svg.zip)

**Comment by defiantgoat** [comment]
Updated as of v 1.1.12

**Comment by marikavertzonis** [comment]
tested on windows 10, ios 8.4 (iphone 6), ios 9.3 (iphone 5), android 6.0.1 (samsung s6), android 7 (nexus 6)
and see clearly disabled arrow.
![disabledarrow](https://cloud.githubusercontent.com/assets/5713624/24485423/1d206640-1550-11e7-95d3-aaa0c92b44e9.PNG)

**Comment by qhui-red** [comment]
Hi @marikavertzonis @defiantgoat , how about only showing the no signal icon?
