### ISSUE TITLE
Scale of settings icon in no destination set message, on Windows, is tool big

### ISSUE THREAD

**Issue by qhui-red** [Esri/Trek2There#30]

**Comment by marikavertzonis** [comment]
tested on windows 10 - with 1.1.10 and scale of icon is good.
![settingsscalefix](https://cloud.githubusercontent.com/assets/5713624/22278631/2062b52e-e319-11e6-9f12-67e321fdb1ea.PNG)
also confirmed its still good on android 4.2 (CT4) and iOS 8.4 (iphone 5).
