### ISSUE TITLE
Direction arrow bounces around

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#31]
Particularly when stopping or starting, the direction arrow does bounce around.
Moving at a steady pace seems to help the arrow rotate smoothly.

More effort is required to improve the arrow behavior, including
- Arrival maths - #3
- Location accuracy indicator could help communicate why the arrow might be bouncing around - #16

**Comment by marikavertzonis** [comment]
This issue is specific to experimental mode, and requires more research, moving out of 3.0 release.

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.25

**Comment by dominikargast** [comment]
Rev e10da17 should have been assigned to #31

**Comment by marikavertzonis** [comment]
- this has significantly improved with recent updates. tested 3.0.32 on ios and android, and when using the compass experimental mode, you see the arrow move more like a mechanical compass (ie: it does jiggle a little but is subtle). 
- the compass indicator is visible when you stop moving, then when you start walking it goes (this is good).
- tested on Sony Xperia Android 7.1.1, Asus ZenFone AR Android 7.0, Samsung S6 Android 6.0.1, iPhone X iOS 11.2.6, Google Pixel 2 Android 8.1
