### ISSUE TITLE
Contrast switch - Sun icon is quite similar to Settings icon - consider alternative to Sun / Moon

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#32]
Day night mode, and subsequently the icons that represent it (sun and moon) are an gross simplicifcation of the tools needs. It really is a contrast switch. It dosnt need to be night time to need the 'night' setting.  See https://github.com/ArcGIS/Trek2There/issues/22#issuecomment-250108430 for more discussion.

The main point of this issue is to review the icon of the Sun. It looks like the Settings tool. Whilst coming up with an alternative icon, consider it as a contrast switch and not day versus night.

**Comment by qhui-red** [comment]
Switcher Icon
[themeswitch.svg.zip](https://github.com/Esri/Trek2There/files/739968/themeswitch.svg.zip)

**Comment by defiantgoat** [comment]
Available as of v 1.1.13

**Comment by marikavertzonis** [comment]
great icon - clear and obvious. tested on tested with 1.1.15 on windows 10, ios 8.4 (iphone 6), ios 9.3 (iphone5), android 6.0.1 (samsung s6), android 7 (nexus 6)
![contrast](https://cloud.githubusercontent.com/assets/5713624/24486604/b8b9fa5c-1556-11e7-8aba-95862108d73b.PNG)
