### ISSUE TITLE
Create Trek2There Custom URL Scheme from a web browser

### ISSUE THREAD

**Issue by IsmaelInRedlands** [Esri/Trek2There#37]
I created a simple app to easily create Trek2There custom URL Schemes from a web browser. Something like this would be useful for people to quickly get started with the app.

https://arcgis.github.io/Trek2There/Trek2ThereWebLauncher.html 

Scott: May be something like this would be useful for the blog post:
1- Install the app
2- Open this URL, point to your destination and launch Trek2There by simply clicking on the map

I can add very quickly some basic functionality to search for an address

@ScottSand

**Comment by marikavertzonis** [comment]
NB: the url is now 
https://esri.github.io/Trek2There/Trek2ThereWebLauncher.html
have added it to readme.
