### ISSUE TITLE
On Windows app linking launches a new instance of the app, even if already open

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#40]
On Windows (tested with 1.0.172) the callback function launches a new instance of the referring app, rather than bringing focus to the already open app.
In my example i used Survey123 to launch Trek2There. When i click end, a new instance of Survey123 is launched.

Also if you are in Survey123 and Trek2There is already open, if you click an app link, a new instance of Trek2There is launched. This was tested as a part of #39. On iOS and Android having Trek2There already opened is a workaround for navigation not starting straight away. That workaround doesn't work on Windows.

**Comment by shobanasuresh** [comment]
>if you are in Survey123 and Trek2There is already open, if you click an app link, a new instance of Trek2There is launched.

@marikavertzonis @dominikargast Above issue can be resolved by setting `appinfo.multipleInstances` to false in Trek2There.

>In my example i used Survey123 to launch Trek2There. When i click end, a new instance of Survey123 is launched.

Survey123 2.6+ builds already sets  `appinfo.multipleInstances` to false.  @marikavertzonis Can you please test with latest Survey123 2.7 Windows build?

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.03

**Comment by marikavertzonis** [comment]
tested with both UWP and Windows x86 builds - UWP didn't have this issue prior to 3.0.3 - Windows x86 did. Now in 3.0.3 Windows x86 no longer launches an additional instance.
- If you already have a destination set (either manually on the setting page, or from a URL link), and launch with a new URL link (with different destination) the destination is changed to the new one (good)
- If you already have a destination set, and launch from the start menu (ie: no new destination) the original destination remains (good).

**Comment by dominikargast** [comment]
The correct issue number for the commit above is #104
