### ISSUE TITLE
Need a new graphic for "Start moving to determine direction" state

### ISSUE THREAD

**Issue by qhui-red** [Esri/Trek2There#41]
In Sep 26 usability testing, I found user keep following the arrow even if it is grayed out. 

Need a new graphic to represent this state. For example, a question mark icon.

**Comment by spatialdude** [comment]
Example of a car navigation system display.

![carnav](https://cloud.githubusercontent.com/assets/7235583/20511290/136ce9e6-b0cb-11e6-8d85-423e32a6ebfd.jpg)

**Comment by marikavertzonis** [comment]
duplicate issue of #25. the new graphic went in version 1.1.
