### ISSUE TITLE
Link to marketplace listing in labs.esri.com is incorrect

### ISSUE THREAD

**Issue by IsmaelInRedlands** [Esri/Trek2There#44]
The Trek2There item in labs.esri.com should link to: https://marketplace.arcgis.com/listing.html?id=a1a3caec68694eaf8b6e0c25f0657275   Currently it is pointing to snap2data.

**Comment by nitinsbajaj** [comment]
I sent it for update at noon, should be done in the am



On Tue, Oct 18, 2016 at 9:44 PM -0700, "Ismael Chivite" <notifications@github.com<mailto:notifications@github.com>> wrote:


The Trek2There item in labs.esri.com should link to: https://marketplace.arcgis.com/listing.html?id=a1a3caec68694eaf8b6e0c25f0657275 Currently it is pointing to snap2data.

-
