### ISSUE TITLE
"Start Moving" notation isn't shown on the start of navigation on some Android devices

### ISSUE THREAD

**Issue by defiantgoat** [Esri/Trek2There#45]
On some Android devices position.directionValid must return true so the statusMessage isn't shown when navigation first starts in order to inform the user to move. This isn't an issue on iOS.

See comment in NavigationView code > https://github.com/Esri/Trek2There/blob/master/NavigationView.qml#L496

**Comment by dominikargast** [comment]
@marikavertzonis With the recent changes to #3 this issue should have been resolved. Please test.

**Comment by marikavertzonis** [comment]
with 3.0.32 am seeing a consistent behavior on these (quite different) 4 android devices:
 - Google Pixel 2 Android 8.1
 - Samsung S6 Android 6.0.1
 - Sony Xperia Android 7.1.1
 - Asus ZenFone AR Android 7.0

when compass mode is enabled, you immediately get an arrow and no 'start moving' message. when compass mode is not enabled, you do get the immediate 'start moving'. the original issue is not clear which devices had the problem. but in general the messaging in the app appears at more appropriate times.
