### ISSUE TITLE
Keyboard dosnt have a minus sign on some Android devices

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#46]
Entering long and lat values require a minus sign, and on some Android devices the default keyboard doesn't have one.
Some model Samsung and LG keyboards suffer from this, but we've seen defaults on Sony, Cedar Tree, Nexus, some Samsung with the minus sign.

Downloading a Google keyboard fixes the issue.

However, if this does pose an an ongoing issue, should consider adding a custom keyboard to the app.

**Comment by spatialdude** [comment]
Ideally we make the input fields parse a variety of ways lats and longs can be input. 

e.g. These all represent the same latitude

-37.5
S 37.5
37.5 S
S 37 30

This doesn't negate the usefulness of a dedicated virtual keyboard for coordinate input.

**Comment by defiantgoat** [comment]
It has been reported that on some Android devices the 'period' key isn't available on the keyboard, so it isn't possible to add a decimal coordinate.

**Comment by marikavertzonis** [comment]
planned changes for #50 will make this issue obsolete. Supporting the multiple coordinate formats means the data entry will be a string and therefore it will force the full keyboard.

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.7

**Comment by marikavertzonis** [comment]
tested 3.0.8 on windows phone 10, windows desktop 10, iphone 6 (ios 10.3.3), trimble tdc (android 6) and in all coordinate format choices i see the full keyboard - and can get access to - and .
