### ISSUE TITLE
Bearing Label

### ISSUE THREAD

**Issue by craigcarps** [Esri/Trek2There#48]
Strong user feedback for a bearing label on the direction arrow has been received. This is to allow for Trek2There to be used in compliment to conventional physical compass use in the field for navigation. 

The workflow would be the user identifies a location to navigate too, Trek2There provides the distance and bearing values. The user puts the electronic device safely back in their bag (this preserves battery life while also keeping the device safe while tramping through thick bush), and uses a physical compass to navigate to the bearing. Trek2There would be pulled out intermittently to check the distance and bearing values.

**Comment by dominikargast** [comment]
Refer to the following designs:
- https://esri.box.com/s/flogor93ghofkcytq6o2becq4a2eqe1r
- https://esri.app.box.com/file/280290192298

**Comment by dominikargast** [comment]
@marikavertzonis please test with build 3.0.4

**Comment by marikavertzonis** [comment]
tested build 3.0.4 with nexus 6p (android), iphone 8 (ios) and windows 10. 
the text is very small, in particular when you turn the device to landscape (which is the default on desktop) there’s a lot of white space around the text. can we make the text block (distance, bearing and accuracy) much bigger to fill the space?

**Comment by marikavertzonis** [comment]
closing this issue for release 3.0. the bearing is now present, and the question about the size is aesthetic. lets get it out in the wild and see how it works. please refrain from reopening this issue to do with how the bearing looks, and instead create a new issue.
