### ISSUE TITLE
Integration between Workforce, Collector and Trek2There

### ISSUE THREAD

**Issue by gradzevicius** [Esri/Trek2There#51]
There is a need that Trek2There would be integrated with Workforce and Collector. It would be very useful navigate to assignment or item.

**Comment by IsmaelInRedlands** [comment]
See this [blog ](https://blogs.esri.com/esri/arcgis/2016/12/22/introducing-trek2there/)for information about launching Trek2There from Collector for ArcGIS and Explorer for ArcGIS while adding the coordinates of your destination. 

 https://blogs.esri.com/esri/arcgis/2016/12/22/introducing-trek2there/

**Comment by marikavertzonis** [comment]
Closing this issue as a duplicate of #47. Some progress made but additional work to be documented in the other issue.
