### ISSUE TITLE
Add QML accessibility parameters to application 

### ISSUE THREAD

**Issue by defiantgoat** [Esri/Trek2There#53]
In order to make application accessible, begin by adding Qt's Accessible parameters to application components.

http://doc.qt.io/qt-5/qml-qtquick-accessible.html

**Comment by marikavertzonis** [comment]
tested with 1.1.15 on windows with narrator enabled. 
some elements of the screen were narrated 'enter latitude' and 'enter longitude'. but other areas where narration was expected (eg: changing distance units from metric to imperial, back arrow) did not have narration.

**to users of accessibility tools** - please create new issues for each problem that you encounter when using trek to there with accessibility tools.
