### ISSUE TITLE
copy/paste lat longs in app for iPhone

### ISSUE THREAD

**Issue by kulasdn** [Esri/Trek2There#55]
Maybe I'm missing something, but I've been trying to simply copy/paste lat longs into Trek2There  on my iPhone and when I tap & hold on the boxes to enter latitude and longitude, the paste option will not appear. I just downloaded Trek2There so I have the latest version. I verified that the coordinates were indeed copied to my clipboard so I'm pretty sure this is not user error. It would be really nice to simply copy/paste these criteria from Collector instead of manually entering, as an alternative to the url method. Copy and pasting DID work on my iPad with the copy/paste button that's on the keyboard, but iPhone has no such button on the keyboard. Thanks for your consideration!

**Comment by defiantgoat** [comment]
Copy and pasting into TextFields with custom styles was a bug that has been fixed with Qt 5.7.  Once we build Trek2There with the newest version of Qt, this bug will be fixed.

**Comment by marikavertzonis** [comment]
new builds with 5.8 appear to fix this. 
tested on iphone6 (ios 8.4) and can successfully copy and paste. As described in #56 you can copy and paste coordinates as either
 - individaul numbers
 - a string eg: `89.44454,-179.34343433`
 - json eg: 
```
{
	"latitude":55.434323,
	"longitude":-33.23533
}
```
