### ISSUE TITLE
Enable Trek2There to listen to the application clipboard for coordinate copying

### ISSUE THREAD

**Issue by defiantgoat** [Esri/Trek2There#56]
If coordinates are copied to the clipboard, allow T2T to listen for data changes and react if the copied data matches the following schemes:

## As JSON in the following format:

{
	"latitude": latitude in decimal coordinates,
	"longitude": longitude in decimal coordinates
}

Example:
```
{
	"latitude":55.434323,
	"longitude":-33.23533
}
```

## As a string in the following format

latitude in decimal coordinates, longitude in decimal coordinates

Example

`-89.44454,-179.34343433`

- Should the application prompt the user to accept the coordiantes?
- Should the user be able to change a setting in the app to not listen to the clipboard?

**Comment by IsmaelInRedlands** [comment]
@defiantgoat  It would not be nice to have Trek2There change the coordinates without a warning. I think prompting the user whenever coords are copied to clipboard is a good thing.

As for the format, it will be hard for the app to figure which coord is lat and which one is lon.

For example, in this case: -89.44454,-79.34343433  which one is which?

**Comment by defiantgoat** [comment]
@IsmaelInRedlands If the user is using a simple string, the responsibility will be on the user to ensure that it is latitude, longitude (y,x).  Clearly if a value is greater than 90 then we could figure out, but that would be impossible to implement consistently.

**Comment by defiantgoat** [comment]
Added ability to swap coordinates that are copied from the clipboard (if they are valid).
![img_0402](https://cloud.githubusercontent.com/assets/3229911/22233652/d9161a9a-e245-11e6-9c57-fe1f73c2b640.jpg)
![img_0403](https://cloud.githubusercontent.com/assets/3229911/22233653/db53d8ec-e245-11e6-94b7-ed0cdb9c4c86.jpg)

**Comment by defiantgoat** [comment]
This functionality is currently only working on iOS. Debugging now for Android.

**Comment by defiantgoat** [comment]
There is no current resolution in the AppFramework to allow this to work in Android devices. As of now, this is only an iOS available feature.

**Comment by marikavertzonis** [comment]
tested with 1.1.14 on ios android and windows. consider as working as expected on iOS and Windows. 

keeping the issue open specifically for android.

**Comment by marikavertzonis** [comment]
with the changes in appframework at version 3.0, on android, we now get the message box 'it looks like you copied coordinates....' but it is not displayed in full and the app extent changes to the size of the message. you can accept the values, they do appear in the settings dialog and you can go back to the full screen view - but the app always stays small (the size of the dialog box).
am testing with 3.0.4 of the app and confirm it works on ios without changing the size of the app window.

![t2t_smalldialog](https://user-images.githubusercontent.com/5713624/37635219-8ac8f4c6-2c4e-11e8-906f-b795a9ac12e6.jpg)

![t2t_smallcoords](https://user-images.githubusercontent.com/5713624/37635222-8b33439e-2c4e-11e8-9fd0-38e028b103a2.jpg)

![t2t_smalldisplay](https://user-images.githubusercontent.com/5713624/37635220-8afd0950-2c4e-11e8-9454-833721d134cd.jpg)

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.6

**Comment by marikavertzonis** [comment]
testing with 3.0.6 works great on android :).

- windows phone - i get a full screen dialog with buttons that are missing the yes no text. if i click the one on the right, the copy does work. so odd ui, but working functionality.
- windows UWP on desktop - i get no dialog, can not copy paste.
- ios - no dialog.

this photo shows windows phone on left, android in middle and iphone on right.

![copy paste dialog](https://user-images.githubusercontent.com/5713624/37751061-4f0ec1bc-2de4-11e8-80bc-e6e70a7fe226.jpg)

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.8

**Comment by marikavertzonis** [comment]
3.0.8 on windows phone 10, windows desktop 10, iphone 6 (ios 10.3.3), trimble tdc (android 6) now i see the same copy paste dialog on all devices and can successfully paste latitude and longitude in decimal coordinates. 

nb: only latitude and longitude in decimal coordinates can be copy and pasted - #50 does introduce support for different coord systems. the finer detail of copy paste with different coords to be fleshed out in that issue and am closing this one.
