### ISSUE TITLE
Arrived too early

### ISSUE THREAD

**Issue by Matronek** [Esri/Trek2There#59]
I had a chance to use Trek2There with a Leica Zeno 20. The Zeno 20 has centimeter accuracy so I was going to try using Trek2There to find buried valve. If I got within 20ft it would say I arrived. Is there a way to make this app never arrive? The Zeno 20 has a program for staking out a point and the direction and distance are constantly changing as you get closer to the object. Trek2There could be used for staking to a point if the arrived message doesn't come up. I think a reset button would work better for this.

**Comment by defiantgoat** [comment]
@Matronek Thanks for your feedback. This is certainly something we will be looking at as we enhance the application.

**Comment by defiantgoat** [comment]
Disabled arrival logic by speed and distance. For this version, the user should never receive the arrival message. If a request is made to re-implement arrival logic and arrival message, the logic can be finessed and re-introduced in a later version.

**Comment by marikavertzonis** [comment]
tested with 2.0.287 to 2.0.301 on 
 - iphone 6 and iphone 5
 - android sony xperia, samsung s6, trimble tdc

and i see that the arrival message never appears. this is quite fine - as I approach my destination the distance does get small(3-5m) and then as i move around and away from it, it grows. This is good. I can successfully click end to go back to my referring app.
