### ISSUE TITLE
Implement HUD navigation

### ISSUE THREAD

**Issue by defiantgoat** [Esri/Trek2There#61]

**Comment by defiantgoat** [comment]
HUD navigation is now enabled in Trek2There. HUD becomes effective when the device is at 30 degrees approximately. The current logic uses GPS only location readings to provide bearing correction information (as it did in version 1). Experimental features can be enabled via the Settings view and will employ the compass for bearing correction at a walking pace and display a marker on the horizon of the HUD.

**Comment by marikavertzonis** [comment]
On windows surface book with 2.0.301 the camera view loads up with front facing camera. it needs to rear camera by default.

**Comment by defiantgoat** [comment]
@marikavertzonis Rear camera selection is fixed with v 2.0.302.

**Comment by marikavertzonis** [comment]
Tested with builds 2.0.276 to 2.0.302 on
 - iphone 6, iphone 5, ipad air
 - android  sony xperia, samsung s6, trimble tdc 100, oppo f1s
 - windows surface book, surface pro
Holding device in portrait and landscape view:
 - Walking - NB: whilst walking its more natural to hold the device near horizontal keeping the app in the original display mode. As you approach the destination (or stop for a spot check) tilting the device up is good to show the destination overlaid on the camera image. With experimental features on
    - As you tilt the device upwards the arrow changes to a perspective view arrow as expected.
    - When experimental features is on - and you are in portrait device orientation - you also get the 'pin'.
    - When experimental features is on - and you are in landscape device orientation - you dont get the 'pin'      there just isn't much room for it. Might be OK on a tablet device, but not on phone.
- In Vehicle - difference between GPS and Compass mode is more noticeable when in vehicle and vehicle starts and stops. Observations show that different devices behavior noticeably different in same scenarios. For example: iphone 6 behaved noticeably better than iphone 5, sony xperia behaved noticeably better than samsung s6. More extensive comparisons will be documented in wiki.
