### ISSUE TITLE
Improve Accuracy Navigation value (centimeters) towards destination point

### ISSUE THREAD

**Issue by pkrejci** [Esri/Trek2There#65]
Hi,
our clients which are most common municipalities of our Company are using the Trek2There navigation to locate GPS measured positions via our WebGIS solution WebOffice [WebOffice & Trek2There](https://www.mysynergis.com/en/news/news/id/1448/) The users want to get the direct route via the Trek2There app to navigate to highly precision measured objects like waterworks valves etc. Therefore the clients are using highly precision GPS instruments (Leica, etc.). 

The issue is if the users are close to the destination the Trek2There software only uses in our case meter to show the distance to the destination. The GPS device can calculate a position with DGPS to a accuracy value of 1 centimetres. Is there an option or would it be possible to change the distance from meters to centimeters if the value is near the destination point to get more information about the position at the last meter.
I know this is only relevant if high precision GPS is used but I think it would enhance the Usability with the use of high precision GPS positions.

Please let me know if you see it the same way and if an implementation or configuration is possible to avoid this behaviour.

Attached you can see the screenshots taken from Trek2There application and the Leica GPS Tool Zeno Connect which shows the accuracy of the position of the high precision GPS device (only some centimetres) and the Trek2There application shows only meter to the destination point and also the accuracy information within Trek2There on the top right side.

![trek2there2](https://user-images.githubusercontent.com/31061355/29374063-6f4e47f2-82b0-11e7-8936-2a51f3856890.png)
![trek2there3](https://user-images.githubusercontent.com/31061355/29374064-6f4f3fd6-82b0-11e7-8754-6d3b2b138dd1.png)

Thank you for your help
Patrick

**Comment by phaedrusakadoctorf** [comment]
Hi Patrick and Defiantgoat,

I'm also looking forward for this feature.
Please keep me in the loop,

cheers

Frederik

**Comment by marikavertzonis** [comment]
Its planned that the new GNSS receiver support coming in AppStudio 2.2 will be integrated in Trek2There to meet the objectives of this issue. To do:
- [ ] Add device browsing page for user to be able to select a connected GNSS receiver
- [ ] Add information page to show direct messages and or GNSS metadata from the receiver for user to be sure the expected accuracy's are being obtained

**Comment by marikavertzonis** [comment]
Design for device browsing and quality information now located at 
https://esri.app.box.com/folder/47302135861

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.15

**Comment by marikavertzonis** [comment]
tested with 3.0.17 on android, ios and windows. the new external device selection is in place, and now when i use a high precision device, i see up to 2 decimal places in the accuracy reported. tested with eos arrow, bad elf pro+ (both give result to 2 decimal places), and the bad elf pro, emtac bt gps and internal position source (give result to 0 decimal places.
