### ISSUE TITLE
Text on Windows is crowded at the bottom of the page

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#69]
Worse in the UWP build than classic Windows build - but both are crowded. Not an issue on iOS and Android.

**UWP:**
![uwptextrunsintobutton](https://user-images.githubusercontent.com/5713624/37372356-8f21eb8c-2766-11e8-82a0-10dd0a1a16e8.PNG)

**Windows x86:**
![windowstextrunsintobutton](https://user-images.githubusercontent.com/5713624/37372342-879ce3e4-2766-11e8-8c8b-123b0d43e0c1.PNG)

**Comment by dominikargast** [comment]
@marikavertzonis this is related to #48 and may have been solved by rev 
365c805. Please test with build 3.0.4

**Comment by marikavertzonis** [comment]
tested 3.0.4 on windows 10 - the default is now the landscape mode so its not obvious - but if you turn the tablet to portrait mode its still crowded as above. also windows phone is still crowded as above.

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.5

**Comment by marikavertzonis** [comment]
tested build 3.0.5 on windows 10 (both UWPx86 and classic Windows build), and windows phone 10 and the spacing is now fixed / as expected
