### ISSUE TITLE
Add Trek2There to the WhiteList of GNSS receiver vendors

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#71]
Emails have been sent today to Bad Elf and Eos. Once response received, protocol strings need to be added to Trek2There as per
http://doc.arcgis.com/en/appstudio/api-guide/apihighaccuracygps.htm#ESRI_SECTION1_1920DD90D17248DE93E90D9164D36344

**Comment by marikavertzonis** [comment]
Responses received from both Bad Elf and Eos, good to add the protocol strings to the app.

**Comment by dominikargast** [comment]
@marikavertzonis please test with 3.0.14

**Comment by marikavertzonis** [comment]
i can see the expected strings in teh app settings, but can not test until app in ios store. test flight is fine too - awaiting resolution to #84 before this

**Comment by marikavertzonis** [comment]
An early adopter has been unsuccessfully trying to connect to a Trimble R2 on iOS. Whitelisting from Trimble requires additional information - refer to discussion here https://devtopia.esri.com/Melbourne/Survey123/issues/421#issuecomment-895476
The Trimble R2 does successfully work with Trek2There on Android.

**Comment by marikavertzonis** [comment]
With Trek2There now in TestFlight, i have download via this platform and can successfully connect to the Bad Elf and Eos devices. 

An early adopter has been unsuccessfully trying to connect to a Trimble R2 on iOS. Whitelisting from Trimble requires additional information - refer to discussion here https://devtopia.esri.com/Melbourne/Survey123/issues/421#issuecomment-895476

Am closing this current issue, but have created new one specifically for Trimble whitelisting #95. After T2T 3.0 release, create new issues for whitelisting of any other GNSS receiver vendors, separately.
