### ISSUE TITLE
Coordinates sent from another app no longer populate the destination

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#72]
I have the following in an old Survey123 survey,
<a href="arcgis-trek2there://?stop=-37.827627, 144.966222&callbackprompt=Survey123&callback=arcgis-survey123://">IGA</a>
and although it launches Trek2There the destination is no longer automatically populated. This worked in previous release.

you can also simulate this by copying the following into a web browser
arcgis-trek2there://?stop=-37.827627,144.966222

**Comment by dominikargast** [comment]
Related to #50

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.17

**Comment by marikavertzonis** [comment]
tested with 3.0.17 on 
 - windows desktop (from survey123 and from a web browser)
 - android - nexus 6, pixel 2, rimble tdc 100
 - ios - iphone6, iphone8
and can successfully launch T2T navigation page with coordinates (note they must be decimal degrees).
