### ISSUE TITLE
Automatically reconnect to external GPS on start up on iOS

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#73]
If an external receiver has been previously connected in Trek2There, when i restart the app, it should automatically connect. Testing with build 3.0.14, it does so on Mac, Windows and Android but not on iOS
On start up on iOS - no device is listed on the settings page, and _use built in location sensor_ is selected instead of _use external receiver_. Same observed on the iphone 6 (iOS 10.3.3) and iphone 8 (iOS 11.3).

**Comment by dominikargast** [comment]
This also affects Android. When the app is closed, the gps device is disconnected, which changes the connection type to "internal". This is stored in the settings before exiting the app.

On reopening the app, the "internal" connection type is read from the settings.

On Mac and probably Windows and Linux, the app is exited before the updated connection type is written do disk.

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.16

**Comment by marikavertzonis** [comment]
tested with 3.1.17 on
 - trimble tdc 100, nexus 6, pixel 2 (android)
 - iphone6 and iphone 8

and all reconnect on startup up to a previously connected external receiver (and show the gps icon on the navigation page).

also if you go to the settings page, switch to use built in location sensor and then switch back to user external receiver, they all successfully reconnect.
