### ISSUE TITLE
When external GPS connection lost, and returns, auto reconnect

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#74]
There are two scenarios where this can readily be observed:

1) **Manual switch between _use external receiver_ and _use built-in location sensor_ on the settings page.** 
    - Start by choosing _use external receiver_  and select a receiver on the discovery page. once successful, see that the receiver is listed under the _use external receiver_ checkbox.
![image](https://user-images.githubusercontent.com/5713624/39557516-8be02330-4ecb-11e8-926c-d2a34a58d79c.png)
     - Now switch to _use built-in location sensor_
     - Switch back to _use external receiver_ . See that no device is listed anymore. I expect to see the previously selected receiver listed. And similar to on startup, the process of connecting to it, to automatically commence.

2) **External receiver switched off whilst on the main screen and using the app**
     - On the settings page choose _use external receiver_ and select a receiver
     - Go to the main page as start trekking to there....
     - Physically turn off your GPS. The lost connection will be identified by the app and it will automatically revert to _use built-in location sensor_. 
     - Turn on your GPS. Re connection should automatically recommence.

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.16

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.17 - T2T should now attempt to connect to external device as soon as the navigation page is displayed

**Comment by marikavertzonis** [comment]
as per https://github.com/Esri/Trek2There/issues/73#issuecomment-386949257 tested with 3.1.17 on
 - trimble tdc 100, nexus 6, pixel 2 (android)
 - iphone6 and iphone 8

connect to external receiver, switch to use built in location sensor and then switch back to user external receiver, they all successfully reconnect.
