### ISSUE TITLE
Add an indicator to the main page to show whether you are using external GNSS or not

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#75]
After testing with early 3.0 builds its clear that we need an indicator to show whether your using external receiver the built-in location sensor.
Even if you have selected _use external receiver_ the external receiver may physically turn off - then you will be automatically returned to using the built-in location sensor.

We also considered identifying whether experimental mode was enabled and therefor if your speed is being used to improve the reading. Text and icons considered, for all combinations see here
https://esri.box.com/s/ctqs4y7ysiwkq69x5y2syebcfft281tq

Consensus was to only add a single indicator (for now), in the top right hand corner, the gps icon from gnss info:
![image](https://user-images.githubusercontent.com/5713624/39612278-62e0b19e-4fa1-11e8-9cad-f4e1bfaa5f35.png)

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.16

**Comment by marikavertzonis** [comment]
testing with 3.0.17 on windows desktop, android and iOS and i see the satellite icon as described above. when the external receiver is physically turned off, i see the icon go away, and then after its turned back on, after a short time the icon is back.
