### ISSUE TITLE
Text on the select external receiver page is too small on some devices

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#76]
Issue observed on 
 - Windows Surface book
 - Nexus 6, trimble tdc100 (Android)

but not on iphone8. see images below

![image](https://user-images.githubusercontent.com/5713624/39679033-fdd23ec6-51da-11e8-827c-7fa6d3fda949.png)

![small text](https://user-images.githubusercontent.com/5713624/39679277-25f001f6-51de-11e8-8212-9b153a302c70.jpg)

**Comment by dominikargast** [comment]
@marikavertzonis tests with build 3.0.23

**Comment by marikavertzonis** [comment]
tested with app 3.0.23 (built on framework 3.1.33)
and see the text sizes are now consistent on the page

![image](https://user-images.githubusercontent.com/5713624/40522601-139460c0-6015-11e8-86bb-022f07a17faf.png)

confirmed on 
 - windows desktop 10 surface book (image above)
 - trimble tdc 100 and nexus 6 (from the original picture
 - also asus zenpad, pixel 2, iphone 8 and x
