### ISSUE TITLE
Prevent nonsense accuracies from being shown on the navigation page

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#77]
The accuracy shown in this screenshot is not useful. It might supposed to be indicating a poor or false accuracy, but it will be better to show no accuracy than this number.
This was found on build 3.0.17

![garbage accuracy](https://user-images.githubusercontent.com/5713624/39684674-df2caa1c-5200-11e8-9276-6ad0bcb126d1.jpg)

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.18

**Comment by marikavertzonis** [comment]
tested 3.0.18 with same receiver (emtac bt gps) and the trimble tdc and i see no more extra large numbers.
