### ISSUE TITLE
Trek2There reports position information of both internal and external sources simultaneously

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#81]
If the PositionSource component is initialised without a specific NmeaSource set, it will use the default position source available on the platform. After connecting to an external GPS by setting the nmeaSource property, the expectation is that only position information from the external device are reported.

This is not true. Position information from the external device AND the default position source are being reported, leading to unexpected jumps in position and accuracy.

Note that this behaviour does not occur if the nmeaSource property of the PositionSource component is set at startup.

**Comment by dominikargast** [comment]
The root cause is https://devtopia.esri.com/Melbourne/appstudio-framework/issues/555

**Comment by marikavertzonis** [comment]
assuming the symptom of this was the continuous flickering between external and internal position sources on android which meant the rapid appearance and disappearance of the 'start moving...' message then this is fixed :). tested on
 - trimble tdc (android 6) 
 - pixel 2 (android 8) 
 - sony xperia (android 7)
 - iphone x (ios 11.2.6)
 - iphone 8 (ios 11.3.1)
 - windows 10 desktop
