### ISSUE TITLE
Clipboard not working on UWP

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#83]
- Similar to the issue observed in Tile Package Kreator https://github.com/Esri/TilePackageKreator/issues/73
- Parent issue in framework https://devtopia.esri.com/Melbourne/appstudio-framework/issues/292
- to repro in Trek2There, copy either of the following to the clipboard whilst Trek2There is open. If you have the Windows Classic build installed you will get a dialog box asking if you want to paste these values into Trek2There. In the UWP build you get no dialog and no pasting.
   
`-89.44454,-179.34343433`

```
   {
	"latitude":55.434323,
	"longitude":-33.23533
  }
```

**Comment by siddeshpillai** [comment]
@marikavertzonis
I can reproduce this error. But this can be handled in the app due to the nature of UWP.

Ref: https://github.com/ArcGIS/MyUSNG/issues/15#issuecomment-395583510

Adding the following in **Trek2There.qml** solves the issue on my UWP app. And I see the dialog 

![image](https://user-images.githubusercontent.com/4101783/41184366-b53fa1a8-6b34-11e8-9618-c28fe5a2e971.png)


```
Connections {
       id: appClipboard
       target: AppFramework.clipboard

       property string inLat: ""
       property string inLon: ""

       onDataChanged: {

           console.log('there is data on the clipboard');

           checkClip()

       }
   }

   Connections {
      target: Qt.application
      onStateChanged: {
         if(Qt.application.state === Qt.ApplicationActive)
         {
            // Application go in active state
             console.log("CALLING checkClip() when the app is active");
             checkClip();
         }
         else
         {
            // Application go in suspend state
         }
      }
   }

   function checkClip() {
       var lat = "";
       var lon = "";

       if (AppFramework.clipboard.dataAvailable && listenToClipboard) {
           try {
               var inJson = JSON.parse(AppFramework.clipboard.text);
               if (inJson.hasOwnProperty("latitude") && inJson.hasOwnProperty("longitude")) {
                   lat = inJson.latitude.toString().trim();
                   lon = inJson.longitude.toString().trim();
               }
           }
           catch(e) {
               if (e.toString().indexOf("JSON.parse: Parse error") > -1) {
                   var incoords = AppFramework.clipboard.text.split(',');
                   if (incoords.length === 2) {
                       lat = incoords[0].toString().trim();
                       lon = incoords[1].toString().trim();
                   }
               }
           }
           finally {
               if (lat !== "" && lon !== "") {
                   if (validCoordinates(lat, lon)) {
                       appClipboard.inLat = lat;
                       appClipboard.inLon = lon;
                       clipboardDialog.clipLat = lat;
                       clipboardDialog.clipLon = lon;
                       clipboardDialog.open();
                   }
               }
           }
       }
   }
```

@defiantgoat Can you try this approach and let me know if this works?

**Comment by marikavertzonis** [comment]
@dominikargast - can you please try this and see if this is a viable option for T2T?

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.34

**Comment by marikavertzonis** [comment]
with 3.0.34 clipboard now working the same on uwp and windows.

note that when you change focus from T2T to another app and then return to T2T, the paste message will appear again with the previously offered coordinates. this this was observed on windows, uwp and mac, and is annoying. its expected that you should only see this offering after you have copied coordinates ready for pasting.

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.35

**Comment by marikavertzonis** [comment]
with 3.0.35 windows and uwp both show the paste dialog when expected, and once you've pasted (or said no in the dialog dismissing the value) you dont get the prompt again (until you next copy something to clipboard).
