### ISSUE TITLE
Crash on startup on iOS

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#84]
Currently believe this crash is related to
https://devtopia.esri.com/Melbourne/appstudio-framework/issues/566
latest version with the crash is 3.0.18 using framework 3.1.24

**Comment by dominikargast** [comment]
@marikavertzonis please test with AppFramework 3.1.33

**Comment by IsmaelInRedlands** [comment]
Tested Trek2There 3.0.23 with Framework 3.1.33
Crash on startup cannot be reproduced anymore on iPhone 8 iOS 11.3.1

**Comment by marikavertzonis** [comment]
I confirm the above, Trek2There 3.0.23 with Framework 3.1.33 didn't crash on our iphone 5, iphone 8, iphone x, ipad air. (also still good on android and windows)
