### ISSUE TITLE
Filter the list in select a device to only show Type 0 devices 

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#86]
Currently bluetooth LE devices are showing up in the select a device list on Android (not on iOS or Windows) - which means I'm seeing the TV and other devices that dont make sense in this app. By design this also the case on UWP, Linux and Mac. 

This device list should be filtered to only show the classic bluetooth devices (these are type 0). 
Its also expected that only paired devices are shown. No additional filtering should required for this, it should be determined by the operating system.

**Comment by dominikargast** [comment]
T2T and GNSS Info filter out Bluetooth LE devices in the displayed devices list. For instance, the device discovery agent finds the following devices (tested on a Mac):

qml: Device discovered - Name: [TV] Samsung 6 Series (55) Type: 0
qml: Device discovered - Name: Bad Elf GPS #001737 Type: 0
qml: Device discovered - Name: DevMac3 Type: 0

qml: Device discovered - Name: [TV] UA85JU7000 Type: 2
qml: Device discovered - Name: Gear S3 (D016) LE Type: 2
qml: Device discovered - Name: Heart Rate (523) Type: 2
qml: Device discovered - Name: Tempo  Type: 2

qml: Device discovered - Name: cu.BadElfGPS143264-Bluetoo-99 Type: 1
qml: Device discovered - Name: tty.BadElfGPS143264-Bluetoo-99 Type: 1
(lots of those)

but displays only the classic bluetooth devices, according to our selection:

<img width="482" alt="screen shot 2018-05-29 at 10 59 52" src="https://user-images.githubusercontent.com/25575734/40633613-1b7750aa-6334-11e8-8db7-f630891786ed.png">

In an interesting twist, the [TV] Samsung 6 Series (55) sometimes is recognised as a Bluetooth LE device and accordingly is not displayed in the list:

qml: Device discovered - Name: Bad Elf GPS #001737 Type: 0
qml: Device discovered - Name: DevMac3 Type: 0

qml: Device discovered - Name: [TV] Samsung 6 Series (55) Type: 2
qml: Device discovered - Name: [TV] UA85JU7000 Type: 2
qml: Device discovered - Name: Gear S3 (D016) LE Type: 2
qml: Device discovered - Name: Heart Rate (523) Type: 2
qml: Device discovered - Name: Tempo  Type: 2

qml: Device discovered - Name: cu.BadElfGPS143264-Bluetoo-99 Type: 1
qml: Device discovered - Name: tty.BadElfGPS143264-Bluetoo-99 Type: 1
(lots of those)

@nandinirao Can Bluetooth devices offer both classic and LE connections at the same time?

**Comment by nandinirao** [comment]
Yes, if they are, Bluetooth Smart devices, they can offer both LE and classic connectivity.

Sent from my iPhone

On May 28, 2018, at 6:40 PM, Dominik Argast <notifications@github.com<mailto:notifications@github.com>> wrote:


T2T and GNSS Info filter out Bluetooth LE devices in the displayed devices list. For instance, the device discovery agent finds the following devices (tested on a Mac):

qml: Device discovered - Name: [TV] Samsung 6 Series (55) Type: 0
qml: Device discovered - Name: Bad Elf GPS #001737 Type: 0
qml: Device discovered - Name: DevMac3 Type: 0

qml: Device discovered - Name: [TV] UA85JU7000 Type: 2
qml: Device discovered - Name: Gear S3 (D016) LE Type: 2
qml: Device discovered - Name: Heart Rate (523) Type: 2
qml: Device discovered - Name: Tempo Type: 2

qml: Device discovered - Name: cu.BadElfGPS143264-Bluetoo-99 Type: 1
qml: Device discovered - Name: tty.BadElfGPS143264-Bluetoo-99 Type: 1
(lots of those)

but displays only the classic bluetooth devices, according to our selection:

[screen shot 2018-05-29 at 10 59 52]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_25575734_40633613-2D1b7750aa-2D6334-2D11e8-2D8db7-2Df630891786ed.png&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=-n8WqXA2D3okd3IvndfleA&m=upSGlRxXN8ajovoH7VoVL2q33TPuiSKuodK6U8lVRos&s=YtWiGP_LkCvg-gbUJd8fhmwfb4c1QmI8vQEuqxhXVmw&e=>

In an interesting twist, the [TV] Samsung 6 Series (55) sometimes is recognised as a Bluetooth LE device and accordingly is not displayed in the list:

qml: Device discovered - Name: Bad Elf GPS #001737 Type: 0
qml: Device discovered - Name: DevMac3 Type: 0

qml: Device discovered - Name: [TV] Samsung 6 Series (55) Type: 2
qml: Device discovered - Name: [TV] UA85JU7000 Type: 2
qml: Device discovered - Name: Gear S3 (D016) LE Type: 2
qml: Device discovered - Name: Heart Rate (523) Type: 2
qml: Device discovered - Name: Tempo Type: 2

qml: Device discovered - Name: cu.BadElfGPS143264-Bluetoo-99 Type: 1
qml: Device discovered - Name: tty.BadElfGPS143264-Bluetoo-99 Type: 1
(lots of those)

@nandinirao<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nandinirao&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=-n8WqXA2D3okd3IvndfleA&m=upSGlRxXN8ajovoH7VoVL2q33TPuiSKuodK6U8lVRos&s=5Hzr4QOlEOlW4-8w7WqqI5_H6Y5yswN63CSzwXBbiM4&e=> Can Bluetooth devices offer both classic and LE connections at the same time?

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.26

**Comment by marikavertzonis** [comment]
tested 3.0.31 on the following devices and successfully only see paired devices on the discovery page. successfully changed between paired devices and connected to them.
 - Samsung S6 Android 6.0.1
 - Google Pixel 2 Android 8.1
 - Asus ZenFone AR Android 7.0
 - Sony Xperia Android 7.1.1
 - Nexus 6P Android 8.0

also confirmed that with 3.0.31 behavior hasn't changed on iOS - still see only paired devices (as expected).
