### ISSUE TITLE
unexpected 'Connected to unknown' message on settings page of iOS

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#87]
This is a new issue - since build 33 - the changing of the **icon on navigation page**, the **text on the settings page** and the **selected device on the search page** do not match.

To repro:
 - select a device on the search page
 - go back to the settings page - see 'Connected to unknown' 
 - go back to the navigation page, the satellite icon appears
 - go back to the settings page - see that its now switch to built in receiver
 - go back to navigation page, see the satellite icon is still there

tested on iphone 8 and x (above happened) and pixel 2, trimble tdc and sony xperia (didn't happen - i see the expected receiver name and can successfully switch between navigation page and settings page seeing the expected text and icon)

**Comment by marikavertzonis** [comment]
its possible this is not just iOS...
doesn't occur on my windows 10 desktop, nor trimble tdc (android 6) and pixel 2 (android 8) - BUT it does on the sony xperia (android 7.1.1).

**Comment by dominikargast** [comment]
@marikavertzonis test with 3.0.24

**Comment by marikavertzonis** [comment]
testing with 3.0.24 on iphone 5 and X and i can successfully switch between the three pages and the expected device remains displayed and no unexpected switching to built-in location sensor.
If i forcefully switch to built-in location sensor and then go back to external, it promptly reconnects to my last connected external device.
