### ISSUE TITLE
App crashes when can not connect to a receiver on Windows

### ISSUE THREAD

**Issue by marikavertzonis** [Esri/Trek2There#88]
Split off from #80, testing with app build 3.0.23. if you attempt to connect to a receiver and cant
 - on **windows** the app 'locks up' and has the message of 'not responding'. theres no dialog to dismiss and you cant just choose another device. the only thing to do is close the app.
 - on **uwp**, after saying no to all the pairing requests, the app crashes

**Comment by dominikargast** [comment]
@marikavertzonis I could not reproduce this issue on windows or uwp. Please retest and/or provide specific instructions on how to reproduce this issue.

**Comment by marikavertzonis** [comment]
testing with 3.0.31 with both uwp and windows builds, and i think the crash appears to be when you try to connect to a different external device when your already connected to another. on uwp the app shuts down, on windows you get the 'not responding' app message.

**Comment by dominikargast** [comment]
Corresponding AppFramework issue: https://devtopia.esri.com/Melbourne/appstudio-framework/issues/608

**Comment by anshuman-mathur** [comment]
Tested Trek2There 3.0.36 Beta from HockeyApp which is built on AppFramework 3.1.58.

- Windows classic app: Trek2There connects to a bluetooth GPS device successfully. However, when we try to change the device and connect to a different bluetooth GPS device, the app becomes non responsive and the title shows 'Not Responding'.

- Windows UWP app: The app does not finish connecting to the bluetooth GPS devices. The spinning image keeps on spinning indefinitely, indicating that the app is trying to connect to the GPS device.

**Comment by JohnHasthorpe** [comment]
@anshuman-mathur - I could replicate the Windows issue, but not UWP. I was able to connect to a Bluetooth device without issues.

**Comment by dominikargast** [comment]
@marikavertzonis Please test with Trek2There or Survey123, AppFramework 3.2.1

**Comment by dominikargast** [comment]
@marikavertzonis Please note that this only concerns Windows platforms, the UWP issue is separate and has been split off to #101

**Comment by dominikargast** [comment]
@anshuman-mathur Please test with Trek2There or Survey123, AppFramework 3.2.10

**Comment by dominikargast** [comment]
@marikavertzonis please retest this issue with the T2T 3.1.4 - I think this was resolved a while ago.

**Comment by marikavertzonis** [comment]
- tested windows trek2there 3.1.4 and successfully switched back and forth between two external receivers 5+ times.
- didn't test uwp at this time as our certificate has expired and we are awaiting a new one (and the  issue with uwp has been split off anyway)
