### ISSUE TITLE
Augmented reality view is shown at app start

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#89]
Augmented reality view is shown at app start even if it is not enabled in the settings. This only affects iOS.

**Comment by dominikargast** [comment]
@marikavertzonis test with build 3.0.30

**Comment by marikavertzonis** [comment]
- tested with 3.0.31 on iphone 6, iphone 8, iphone x and ipad air 2 and the aug rel view no longer appears on startup.
- switching the aug rel on, enables it as expected (and disable also works as expected).
- also confirm that no unexpected change has happened on android with these changes - tested on pixel2, sony xperia and asus zenfone.
