### ISSUE TITLE
Inform the user that the compass is being used

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#90]
Due to uncertainties in determining the compass direction (bad calibration, noisy readouts, unknown magnetic declination) the user should be informed if the compass is in use, compared to the direction of travel from the GPS.

This is only an issue if the compass is activated in the experimental settings.

Suggested is to put a small icon, e.g. a compass needle, next to the icon showing connection to an external GPS.

**Comment by marikavertzonis** [comment]
- tested 3.0.32 on ios and android, and when using the compass experimental mode, you see the arrow move more like a mechanical compass (ie: it does jiggle a little but is subtle). 
- the compass indicator is visible when you stop moving, then when you start walking it goes (this is good).
- tested on Sony Xperia Android 7.1.1, Asus ZenFone AR Android 7.0, Samsung S6 Android 6.0.1, iPhone X iOS 11.2.6, Google Pixel 2 Android 8.1
