### ISSUE TITLE
Remember DeviceDiscoveryAgent settings

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#93]
The "detect bluetooth" and "detect USB/COM" settings of the DeviceDiscoveryAgent should be remembered from one session to the next.

In addition, sort the list of detected devices so that bluetooth devices stay on top of the list. Presently, COM port detection is almost instantaneous, whereas bluetooth detection takes some time, resulting in the bluetooth devices being added to the end of the list.

This issue does not affect iOS and Android since COM port detection is disabled on these devices.

**Comment by dominikargast** [comment]
@marikavertzonis please test with build 3.0.33

**Comment by marikavertzonis** [comment]
to started, tested on linux with AppStudio 3.0.50 and Trek2There 3.0.33. Connected to USB GPS,closed the app, reopened the app, and the USB connection was remembered.

**Comment by marikavertzonis** [comment]
further testing with 3.0.35 (appframework 3.1.52)
 - windows and mac - successfully connect to USB GPS, close app, reopen app, USB connection remembered
 - uwp - known issue with not being able to connect to USB GPS in UWP - https://devtopia.esri.com/Melbourne/appstudio-framework/issues/475
