### ISSUE TITLE
Feature request: Add current coordinates to the display

### ISSUE THREAD

**Issue by dominikargast** [Esri/Trek2There#99]
From Sathya - Add a page which displays the current coordinates:

I was recently asked if AppStudio could be used to build such an app: https://itunes.apple.com/us/app/my-gps-coordinates/id945482414?mt=8
 
My immediate reaction was this one screen app fits nicely in Trek2Threre and does not warrant a new app. The more I think the more I feel that adding this view of current coordinates with other useful info which can be copied and shared would be very useful.
 
-Sathya
 
Sathya Prasad
Group Engineering Manager & Software Development Lead
AppStudio + Esri Labs + Mercator + Survey123 + Story Maps
Esri, Redlands, California
909-793-2853 | @sathyaprasad

**Comment by dominikargast** [comment]
A location info page is now accessible by pressing the satellite icon. This is a byproduct of reworking the location settings UI (#104).

**Comment by dominikargast** [comment]
@marikavertzonis the location status pages lists the current position (press on the satellite icon). Clicking on the `Latitude`, `Longitude`, or `USNG` changes to different coordinate formats (e.g. DD, DDMS, ...). Please test using 3.1.14

**Comment by marikavertzonis** [comment]
testing with 3.1.15 on nokia 8 (android 10) and iphone 8 (ios 13.3.1) with the bad elf pro+ and juniper geode and internal location provider
- i see tapping Latitude, Longitude changes to DDM then DD then back to DMS
- i see tapping USNG changes to MGRS then to UTM/UPS then back to USNG
